### ISSUE TITLE
Reddit API limiting

### ISSUE THREAD

**Issue by endeavor51** [pythonInRelay/Shreddit#9]
Reddit has limited all API interactions on write actions (including edit) to once per ~28-30 seconds.  Attempting to edit twice in that time frame produces a 429 error.  [One of many Reddit posts on the issue.](https://www.reddit.com/r/help/comments/me4ydk/getting_throttled_by_reddit_error_status_429/)

It's not limited to apps like Shreddit (old.reddit.com, 3rd Party Apps also hang here).

Can you add code delay Shreddit's processing of edits by a variable included in the shreddit.yml file so we can adapt to future activities by Reddit admins (ex: if they increase/decrease the limits).

Thanks

**Comment by endeavor51** [comment]
Not fixed.

https://old.reddit.com/r/redditdev/comments/mg077m/not_even_close_to_hitting_the_rate_limitbut_still/gstd506/

`Hey folks - this is in fact a new rate limit on editing of posts/comments, which is similar to how the posting/commenting rate limit exists (in that it is a separate, stricter limit from the API rate limit).

The limit is currently 1 edit every 30 seconds, but we may adjust it up or down without warning.`

**Comment by ggscott** [comment]
According to them lower in the post (14 minutes ago as I type this); Fixed.

https://old.reddit.com/r/redditdev/comments/mg077m/not_even_close_to_hitting_the_rate_limitbut_still/gstm1a9/ <https://old.reddit.com/r/redditdev/comments/mg077m/not_even_close_to_hitting_the_rate_limitbut_still/gstm1a9/>

**Comment by endeavor51** [comment]
I stand corrected, thanks.

**Comment by endeavor51** [comment]
Not sure if it's the same, or some interaction with PRAW, but I just got the below error:


Traceback (most recent call last):
  File "C:\Python39\Scripts\shreddit-script.py", line 33, in <module>
    sys.exit(load_entry_point('shreddit==6.0.7', 'console_scripts', 'shreddit')())
  File "C:\Python39\lib\site-packages\shreddit\app.py", line 45, in main
    shredder.shred()
  File "C:\Python39\lib\site-packages\shreddit\shredder.py", line 68, in shred
    deleted = self._remove_things(self._build_iterator())
  File "C:\Python39\lib\site-packages\shreddit\shredder.py", line 171, in _remove_things
    self._remove(item)
  File "C:\Python39\lib\site-packages\shreddit\shredder.py", line 142, in _remove
    self._remove_comment(item)
  File "C:\Python39\lib\site-packages\shreddit\shredder.py", line 128, in _remove_comment
    comment.edit(replacement_text)
  File "C:\Python39\lib\site-packages\praw\models\reddit\mixins\editable.py", line 47, in edit
    updated = self._reddit.post(API_PATH["edit"], data=data)[0]
  File "C:\Python39\lib\site-packages\praw\reddit.py", line 752, in post
    return self._objectify_request(
  File "C:\Python39\lib\site-packages\praw\reddit.py", line 665, in _objectify_request
    return self._objector.objectify(
  File "C:\Python39\lib\site-packages\praw\objector.py", line 157, in objectify
    raise RedditAPIException(errors)
praw.exceptions.RedditAPIException: RATELIMIT: "Looks like you've been doing that a lot. Take a break for 29 seconds before trying again." on field 'ratelimit'

**Comment by d0t1q** [comment]
created a pull request, essentially just needed to add a sleep 30 to any function that edits something

https://old.reddit.com/r/redditdev/comments/mg077m/not_even_close_to_hitting_the_rate_limitbut_still/gstd506/

"The limit is currently 1 edit every 30 seconds"

**Comment by ashleyconnor** [comment]
It might be better to just allow the cool down time and size to be configurable:

https://github.com/ashleyconnor/Shreddit/commit/71068400f479b2fa9eb3c124feaaaf977c04b3a6

**Comment by KenMacD** [comment]
In your `praw.ini` you may want to set `ratelimit_seconds=45` (or something > 30), the default is 5 seconds which causes the error when the API says to wait longer.

**Comment by xb4r7x** [comment]
This is definitely still happening. @KenMacD  `ratelimit_seconds=45` in my praw.ini didn't seem to do anything. Did I miss something?

**Comment by diversionmary** [comment]
> In your `praw.ini` you may want to set `ratelimit_seconds=45` (or something > 30), the default is 5 seconds which causes the error when the API says to wait longer.

This seems to work.  I added below the [username] that contains the username I'm scrubbing. I also added a [DEFAULT] section at the top of my praw.ini.

**Comment by xb4r7x** [comment]
This is apparently a fairly new feature to the praw library. If anyone else tried the above and it didn't work, try `pip3 install --upgrade praw ` - it should work after that.

**Comment by ashleyconnor** [comment]
Nice find @KenMacD.

**Comment by SkilledAlpaca** [comment]
Unfortunately I'm still getting hit with the rate limit after updating praw (Version: 7.2.0) (`pip3 install --upgrade praw`) and adding `ratelimit_seconds=45` to the `praw.ini` file.

**Comment by diversionmary** [comment]
> Unfortunately I'm still getting hit with the rate limit after updating praw (Version: 7.2.0) (`pip3 install --upgrade praw`) and adding `ratelimit_seconds=45` to the `praw.ini` file.

In addition to [DEFAULT] can you try adding it under your [username] section?

Here's mine:

`[DEFAULT]
ratelimit_seconds=31

[myredditusername]
client_id=foo
client_secret=abc
username=bar
password=xyz
ratelimit_seconds=31`

**Comment by scottjl** [comment]
where are you adding it? i put mine right after [default] and it's working fine for all accounts listed in my praw.ini

```
[default]
ratelimit_seconds=45
...
```

**Comment by SkilledAlpaca** [comment]
```
# Credentials go here. Fill out default, or provide one or more names and call shreddit with the -u option to specify
# which set to use.
[DEFAULT]
ratelimit_seconds=31

[redacted]
client_id=redacted
client_secret=redacted
username=redacted
password=redacted
ratelimit_seconds=31
```

This is my `praw.ini` file.

**Comment by scottjl** [comment]
maybe only put it in one location? and increase it to 45? my file:

```
[default]
ratelimit_seconds=45
client_id=blahblah
client_secret=blahblah
username=blahblah
password=blahblah
[secondredditid]
client_id=blahblah2
client_secret=blahblah2
username=blahblah2
password=blahblah2
```

**Comment by madebycm** [comment]
> 
> 
> This is apparently a fairly new feature to praw. If anyone else tried the above and it didn't work, try `pip3 install --upgrade praw ` - it should work after that.

This is exactly it, great find.

**Comment by SkilledAlpaca** [comment]
> 
> 
> maybe only put it in one location? and increase it to 45? my file:
> 
> ```
> [default]
> ratelimit_seconds=45
> client_id=blahblah
> client_secret=blahblah
> username=blahblah
> password=blahblah
> [secondredditid]
> client_id=blahblah2
> client_secret=blahblah2
> username=blahblah2
> password=blahblah2
> ```

Same issue, and it seems to be failing even quicker now. Sorry for my delayed response. 
`praw.exceptions.APIException: RATELIMIT: 'Looks like you've been doing that a lot. Take a break for 3 seconds before trying again.' on field 'ratelimit'`

**Comment by scottjl** [comment]
@SkilledAlpaca maybe the delay is different per account or how often you try? try upping your ratelimit to 60 and only run it once a day. i only run mine once a day thru cron in the middle of the night.

**Comment by actualcannibal** [comment]
This appears to still be a problem. I ran the recommended solutions in this thread (sudo pip3 install --upgrade praw) and (add ratelimit_seconds=60 to praw.ini), but neither seem to be doing the trick. Still getting the exception:

raise APIException(*errors[0])
praw.exceptions.APIException: RATELIMIT: 'Looks like you've been doing that a lot. Take a break for 3 seconds before trying again.' on field 'ratelimit'

**Comment by amitai** [comment]
Thank you @KenMacD for the workaround - I put `ratelimit_seconds=31` right below `[default]` in praw.ini and it works great (albeit over 6 times slower, obviously).

**Comment by endeavor51** [comment]
Marking as closed as this seems to work for many. Will reopen if this problem reoccurs.

**Comment by clorteau** [comment]
> In your `praw.ini` you may want to set `ratelimit_seconds=45` (or something > 30), the default is 5 seconds which causes the error when the API says to wait longer.

THANK YOU

**Comment by r-tokarski** [comment]
For me, this never worked. I've tried on my Fedora, I've tried on freshly set Ubuntu VM. The `ratelimit_seconds` is simply ignored and scripts always tries to delete comments ASAP.

**Comment by xb4r7x** [comment]
Check your versions.

This is a newer feature and will be ignored with earlier versions of praw

**Comment by r-tokarski** [comment]
> Check your versions.
> This is a newer feature and will be ignored with earlier versions of praw

```
$ dnf info python3-praw | grep Versión   
Versión      : 7.4.0
$ pip3 list | grep praw                  
praw                 7.6.0
prawcore             2.3.0
```
